- name: Remove our server from Red Hat
  hosts: aap
  become: true
  become_user: root

  tasks:

    - name: Red Hat Subscription Manager
      tags:
        - remove
      ansible.builtin.include_role:
        name: rhsm

- name: Remove our infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Include the vm role
      tags:
        - remove
      ansible.builtin.include_role:
        name: vm

    - name: Include the vpc role
      tags:
        - remove
      ansible.builtin.include_role:
        name: vpc

    - name: Include the inventory role
      tags:
        - remove
      ansible.builtin.include_role:
        name: inventory
